softlogo_cms:
  section_types:
    intro: Intro.html.twig  
    intro2: Intro2.html.twig  
    customers: Customers.html.twig
    details: Details.html.twig
    icons_big: Duze-Ikony.html.twig
    icons_small: Icons-Small.html.twig
    gallery: Gallery.html.twig
    contact_map: Contact-Map.html.twig                          
    contact_form: Contact-Form.html.twig
    contact_address: Contact-Address.html.twig
    first_content: First-Content.html.twig
    first_header: First-Header.html.twig
    section_header: Section-Header.html.twig
    team: Team.html.twig
    third_header: Third-Header.html.twig
    work: Work.html.twig
    gallery_item: Gallery-Item.html.twig
    articles: Article.html.twig
    articles_main: Article-Main.html.twig
    slider6_left: Slider6-Left.html.twig
    slider4_right: Slider4-Right.html.twig
  page_types:
    page: page.html.twig
    contact: contact.html.twig
    home: home.html.twig
  block_types:
    sections: Sections.html.twig
    content: Content.html.twig
    header: Standard.html.twig
  article_types:
    main: main
    slave: slave
