softlogo_cms:
  section_types:
    articles: Article.html.twig
  page_types:
    page: page.html.twig
    contact: contact.html.twig
    home: home.html.twig
  block_types:
    sections: Sections.html.twig
    content: Content.html.twig
    header: Standard.html.twig
  article_types:
    Główny-Artykuł: main
    Portfolio-Opis: more
    Portfolio-zakres-prac: pencil
    Portfolio-technologia: wrench
    Portfolio-strona-internetowa: home
    Offer-Strony-internetowe: desktop
    Offer-Sklepy-internetowe: shopping-cart
    Offer-Identyfikacja-wizualna: briefcase
    Offer-Pozycjonowanie: signal
    Offer-Aplikacje-dedykowane: puzzle-piece
    Offer-Strony-responsywne: tablet
    Offer-systemy-rezerwacji: plane
    Offer-CRM: cogs
    Offer-Wyszukiwarki-internetowe: search
    Offer-Audyt: check
    Websites-Project: lemon
    Websites-CMS: edit
    Websites-HTML5/CSS3: html5
    Websites-SEO: signal
    Websites-Support: wrench
    Websites-Responsibility: tablet
  wrapper_types:
    col-lg-12: col-lg-12
    col-lg-8: col-lg-8
    col-lg-6: col-lg-6
    col-lg-3: col-lg-3
    col-lg-2: col-lg-2
  offset_types:
    col-md-offset-1: col-md-offset-1
    col-md-offset-2: col-md-offset-2
    col-offset-3: col-md-offset-3
    col-offset-4: col-md-offset-4
  menu_types:
    bootstrap: Menu-Bootstrap.html.twig
    simple: Menu-Simple.html.twig
    simple-site: Menu-Simple-Site.html.twig
    flat: Menu-Flat.html.twig
