softlogo_cms_routing:
    resource: "@SoftlogoCMSBundle/Resources/config/routing/page.yml"
    prefix:   /{_locale}/
    defaults: { _locale: %locale% }
    requirements:
        _locale: en|pl|de|ru

SoftlogoCMSBundle_sitemap:
    defaults: { _controller: "SoftlogoCMSBundle:Sitemap:index" }
    pattern:  /sitemap.xml

form:
    pattern: /form
    defaults: { _controller: SoftlogoCMSBundle:Contact:form }

form-informacja:
    pattern: /form-informacja
    defaults: { _controller: SoftlogoCMSBundle:Contact:informacja}


cms_section_paging:
    path:     /section/{id}
    defaults: { _controller: SoftlogoCMSBundle:Section:paging }

cms_section_paging_number:
    path:     /section/{id}/page/{pageNumber}
    defaults: { _controller: SoftlogoCMSBundle:Section:paging }

cms_section_show:
    path:     /section/{id}/show
    defaults: { _controller: SoftlogoCMSBundle:Section:show }


