home:
    pattern:  /
    defaults: { _controller: "SoftlogoCMSBundle:Page:show" }

SoftlogoCMSBundle_sitemap:
    defaults: { _controller: "SoftlogoCMSBundle:Sitemap:index" }
    pattern:  /sitemap.xml

SoftlogoCMSBundle_section:
    resource: "@SoftlogoCMSBundle/Resources/config/routing/section.yml"
    prefix:   /section

form:
    pattern: /form
    defaults: { _controller: SoftlogoCMSBundle:Contact:form }

form-informacja:
    pattern: /form-informacja
    defaults: { _controller: SoftlogoCMSBundle:Contact:informacja}

page:
    pattern:  /{anchor}
    defaults: { _controller: "SoftlogoCMSBundle:Page:show" }


show:
    path:     /section/{id}/show
    defaults: { _controller: SoftlogoCMSBundle:Section:show }
