home:
    pattern:  /
    defaults: { _controller: "SoftlogoCMSBundle:Page:show" }

SoftlogoCMSBundle_sitemap:
    defaults: { _controller: "SoftlogoCMSBundle:Sitemap:index" }
    pattern:  /sitemap.xml

form:
    pattern: /form
    defaults: { _controller: SoftlogoCMSBundle:Contact:form }

form-informacja:
    pattern: /form-informacja
    defaults: { _controller: SoftlogoCMSBundle:Contact:informacja}

cms_strony_internetowe:
    pattern: /strony_internetowe
    defaults: { _controller: SoftlogoCMSBundle:Page:show, site: "strony-internetowe", anchor: "strony-internetowe" }

cms_page:
    pattern:  /{anchor}
    defaults: { _controller: SoftlogoCMSBundle:Page:show }

cms_site_page:
    pattern:  /{site}/{anchor}
    defaults: { _controller: SoftlogoCMSBundle:Page:show }

cms_section_paging:
    path:     /section/{id}
    defaults: { _controller: SoftlogoCMSBundle:Section:paging }

cms_section_paging_number:
    path:     /section/{id}/page/{pageNumber}
    defaults: { _controller: SoftlogoCMSBundle:Section:paging }

cms_section_show:
    path:     /section/{id}/show
    defaults: { _controller: SoftlogoCMSBundle:Section:show }


