<?php

namespace Softlogo\CMSBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PageSectionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageSectionRepository extends EntityRepository
{

}
