<?php

namespace Softlogo\CMSBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageRepository extends EntityRepository
{
	public function findBySiteName($name){
		$qb = $this->createQueryBuilder('p')
			->join('p.site', 's');
        $qb->andWhere('s.name= :name')
            ->setParameter('name', $name);
		return $qb;
	}
}
