home:
    pattern:  /
    defaults: { _controller: "SoftlogoCMSBundle:Page:show" , anchor: "home"  }
cms_page:
    pattern:  /{anchor}
    defaults: { _controller: SoftlogoCMSBundle:Page:show }
cms_site_page:
    pattern:  /{site}/{anchor}
    defaults: { _controller: SoftlogoCMSBundle:Page:show }
